# Generated by Django 5.0.3 on 2024-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
