# Generated by Django 5.0.3 on 2024-04-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='added_to_cart',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
