# Generated by Django 5.0.3 on 2024-04-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_fooditem_added_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='added_to_cart',
        ),
    ]
